repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|ts)$
        types: [file]
        exclude: ^(examples/|scripts/|tests/|jest\.config\.js|.*\.config\.(js|cjs|mjs))
        additional_dependencies:
          - eslint@8.56.0
          - typescript@5.8.2
          - '@typescript-eslint/eslint-plugin@6.21.0'
          - '@typescript-eslint/parser@6.21.0'
          - eslint-plugin-import@2.29.1

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|ts|json|yaml|yml)$
        types: [file]
        exclude: ^(examples/|scripts/)
        additional_dependencies:
          - prettier@3.1.0

  # Check project structure
  - repo: local
    hooks:
      - id: check-project-structure
        name: Check Project Structure
        description: Validate project structure follows established guidelines
        language: node
        entry: node
        args: [./scripts/check-project-structure.cjs]
        pass_filenames: false
        always_run: true

  # Type checking with TypeScript - only for src
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript Check
        language: node
        entry: node
        args:
          ['node_modules/typescript/lib/tsc.js', '--noEmit', '--project', './tsconfig.check.json']
        pass_filenames: false
        files: ^src/
        types: [ts]
